### ISSUE TITLE
Hey, sorry for the random issue...

### ISSUE THREAD

**Issue by GriffGreen** [Majoolr/ethereum-contracts#2]
I'm actually trying to get a hold of you because I want to connect with you and give you some WHG tokens which will give you a small share in the donations we received.

Reply here with an address :-D Also... maybe I will see you in Devcon?

**Comment by Hackdom** [comment]
No problem! Email me at hackdom@protonmail.com .

I can't make Devcon b/c of prior commitments, unfortunately, but I WILL be at future events, we should keep in touch, I'd like to meet everyone at some point!
